// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEPn7BtYWu52uyo4Y6xfD5jHg5j0iQRw8',
    appId: '1:1058680587089:web:0b102e4009326abcbac970',
    messagingSenderId: '1058680587089',
    projectId: 'laza-ecommers',
    authDomain: 'laza-ecommers.firebaseapp.com',
    storageBucket: 'laza-ecommers.firebasestorage.app',
    measurementId: 'G-VV50P1WR0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Vh-x_JMRXBKkW6RgB6EaTrv5MVZ20zc',
    appId: '1:1058680587089:android:569ac9924a61436cbac970',
    messagingSenderId: '1058680587089',
    projectId: 'laza-ecommers',
    storageBucket: 'laza-ecommers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-LjehGc1Xz8OPEbAQWLXkyGAeICg24es',
    appId: '1:1058680587089:ios:d5e2118dc12a0d9dbac970',
    messagingSenderId: '1058680587089',
    projectId: 'laza-ecommers',
    storageBucket: 'laza-ecommers.firebasestorage.app',
    iosBundleId: 'com.example.testprojectnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-LjehGc1Xz8OPEbAQWLXkyGAeICg24es',
    appId: '1:1058680587089:ios:d5e2118dc12a0d9dbac970',
    messagingSenderId: '1058680587089',
    projectId: 'laza-ecommers',
    storageBucket: 'laza-ecommers.firebasestorage.app',
    iosBundleId: 'com.example.testprojectnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEPn7BtYWu52uyo4Y6xfD5jHg5j0iQRw8',
    appId: '1:1058680587089:web:8d967e79cb198a18bac970',
    messagingSenderId: '1058680587089',
    projectId: 'laza-ecommers',
    authDomain: 'laza-ecommers.firebaseapp.com',
    storageBucket: 'laza-ecommers.firebasestorage.app',
    measurementId: 'G-FZN4S1MKT1',
  );
}
